"""adds user answer streak fields

Revision ID: ef81c280274a
Revises: e6940cc4bf7a
Create Date: 2022-08-08 03:00:40.081997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef81c280274a'
down_revision = 'e6940cc4bf7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_answer', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('answer_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'answer_streak')
    op.drop_column('users', 'last_answer')
    # ### end Alembic commands ###
