name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build -t test --target test .

      - name: Run linter
        run: docker run test flake8

      - name: Run tests
        run: |
          docker run -v "$(pwd)/tests/reports":"/app/tests/reports" test
          sed -i 's%\/app%'`pwd`'%g' tests/reports/cov.xml 

      - name: Download reporter
        run: |
          curl -L -O https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./test-reporter-latest-linux-amd64

      - name: Upload Coverage
        run: |
          ./test-reporter-latest-linux-amd64 format-coverage --input-type coverage.py -o ./tests/reports/coverage ./tests/reports/cov.xml
          ./test-reporter-latest-linux-amd64 --input $(pwd)/tests/reports/coverage --id ${{secrets.CC_TEST_REPORTER_ID}} upload-coverage
